openapi: 3.0.0
info: 
  title: STD24108
  version: 1.0.0
  description: "This is a specification of STD24108"
servers: 
  - url: "http://localhost:8000"
paths: 
  /health:
    get: 
      response:
          '200'
      description: OK 
      content: 
      text/plain:
      schema:
        type: string
        example: "ok"
  /phones:
    post:
    response: 
        '201'
    description: created
