openapi: 3.0.0
info: 
  title: STD24108
  version: 1.0.0
  description: "This is a specification of STD24108"
servers: 
  - url: "http://localhost:8000"
paths: 
  /ping:
    get: 
    Response:
          '200'
    description: OK 
    content: 
      text/plain:
    schema:
        type: string
        example: pong
    